[build]
  base = "frontend"  # ğŸ”¥ frontend í´ë”ë¥¼ ë¹Œë“œ ê¸°ë³¸ ê²½ë¡œë¡œ ì„¤ì •
  command = "npm run build-storybook"
  publish = "storybook-static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  