name: Dev Branch CI/CD

on:
  push:
    branches: [ "be" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Copy application.yml to backend
      run: echo "${{ secrets.APPLICATION_YML }}" > backend/src/main/resources/application.yml

    - name: Build JAR with Gradle
      run: ./gradlew bootJar
      working-directory: backend

    - name: Build Docker Image
      run: docker build -t onu:latest .
      working-directory: backend

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag onu:latest ${{ secrets.DOCKERHUB_USERNAME }}/onu:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/onu:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop onu-container || true
          docker rm onu-container || true
          docker rmi scc9811/onu || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/onu:latest
          docker run -d -p 8080:8080 --network host --name onu-container ${{ secrets.DOCKERHUB_USERNAME }}/onu
        


          
